Fog/Controllers/SaleController.cs
using Microsoft.AspNetCore.Mvc;
using Fog.Models;

namespace Fog.Controllers
{
    public class SaleController : Controller
    {
        public IActionResult CreateSale()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateSale(SaleModel sale)
        {
            int gameID = DataLibrary.DataAccess.SQLDataAccess.getGameID(sale.SaleGame);
            if (gameID > 0)
            {
                DataLibrary.Models.SaleModel saleData = new DataLibrary.Models.SaleModel();
                saleData.SaleDate = sale.SaleDate.GetValueOrDefault();
                saleData.SalePercent = sale.SalePercent.GetValueOrDefault();
                saleData.SaleGameID = gameID;
                DataLibrary.DataAccess.SQLDataAccess.CreateSale(saleData);
                return RedirectToAction("AdminHome", "Home");
            }
            else
            {
                ModelState.AddModelError("Game", "The game was not found. Please check the game and try again.");
                return View(sale);
            }
        }
    }
}

Fog/Views/Admin/AdminHome.cshtml
@{
    ViewData["Title"] = "Admin Page";
}

<h1 align="center">Admin Page</h1>

<form>
    <br><br>

    <div style="background-color: #ffffff; width: 50%; height: 50%; margin: auto;" align="center">

        <button type="submit" class="btn btn-dark btn-block" style="border-color: #808080;"
                asp-controller="Sale" asp-action="CreateSale">
            Create Sale
        </button>
        <br>
        <button type="submit" class="btn btn-dark btn-block" style="border-color: #808080;"
                asp-controller="Competition" asp-action="CreateCompetition">
            Create Competition
        </button>
        <br>
        <button type="submit" class="btn btn-dark btn-block" style="border-color: #808080;"
                asp-controller="Login" asp-action="CreateDev">
            Create Developer
        </button>
        <br>
        <button type="submit" class="btn btn-dark btn-block" style="border-color: #808080;"
                asp-controller="Login" asp-action="CreateAdmin">
            Create Administrator
        </button>
        <br>
        <button type="submit" class="btn btn-dark btn-block" style="border-color: #808080;"
                asp-controller="Admin" asp-action="EditAdmin">
            Edit Profile
        </button>
        <br>
        <button type="submit" class="btn btn-dark btn-block" style="border-color: #808080;"
                asp-controller="Admin" asp-action="AdminStats">
            Statistic
        </button>

    </div>
</form>

Fog/Views/Admin/AdminStats.cshtml
@model DataLibrary.Models.AdminStatsModel
@{
    ViewData["Title"] = "Statistics";
}

<h1>Statistics</h1>

<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#Game">Game</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#Genre">Genre</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#Developer">Developer</a>
    </li>
</ul>

<div class="container-fluid">
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade show active" id="Game">
            <table class="table table-responsive-sm table-hover">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayName("Game Name")
                        </th>
                        <th>
                            @Html.DisplayName("Purchase")
                        </th>
                        <th>
                            @Html.DisplayName("Total")
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @*Iterating Game ViewModel *@
                    @foreach (var item in Model.Game)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Title)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Purchases)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Total)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="Genre">
            <table class="table table-responsive-sm table-hover">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayName("Genre")
                        </th>
                        <th>
                            @Html.DisplayName("Purchase")
                        </th>
                        <th>
                            @Html.DisplayName("Total")
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @*Iterating Genre ViewModel *@
                    @foreach (var item in Model.Genre)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Genre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.purchases)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Total)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="Developer">
            <table class="table table-responsive-sm table-hover">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayName("Developer")
                        </th>
                        <th>
                            @Html.DisplayName("Purchase")
                        </th>
                        <th>
                            @Html.DisplayName("Total")
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @*Iterating Developer ViewModel *@
                    @foreach (var item in Model.Devs)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.DevName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Purchase)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Total)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Fog/Views/Admin/CreateSale.cshtml
@model Fog.Models.SaleModel

@{
    ViewData["Title"] = "Create Sale";
}

<h1>CreateSale</h1>

@if (TempData["Success"] != null)
{
    <p class="alert alert-success" id="successMessage">@TempData["Success"]</p>
}
@if (TempData["Danger"] != null)
{
    <p class="alert alert-danger" id="dangerMessage">@TempData["Danger"]</p>
}

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateSale">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SalePercent" class="control-label"></label>
                <input asp-for="SalePercent" class="form-control" />
                <span asp-validation-for="SalePercent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SaleDate" class="control-label"></label>
                <input asp-for="SaleDate" class="form-control" />
                <span asp-validation-for="SaleDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SaleGame" class="control-label"></label>
                <input asp-for="SaleGame" class="form-control" />
                <span asp-validation-for="SaleGame" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Fog/Views/Admin/EditAdmin.cshtml
@model Fog.Models.PlayerModel
@{
    ViewData["Title"] = "Edit Admin";
}

<h1>@ViewBag.Title</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="EditAdmin">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" readonly />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DisplayName" class="control-label"></label>
                <input asp-for="DisplayName" class="form-control" />
                <span asp-validation-for="DisplayName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>