Fog/Controllers/CompetitionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

using Fog.Models;

namespace Fog.Controllers
{
    public class CompetitionController : Controller
    {
        public IActionResult CreateCompetition()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateCompetition(CompetitionModel newComp)
        {
            int gameID = DataLibrary.DataAccess.SQLDataAccess.getGameID(newComp.GameTitle);

            if (gameID < 0)
                ModelState.AddModelError("Game", "The game was not found. Please check the game and try again.");

            if(ModelState.IsValid)
            {
                DataLibrary.Models.CompetitionModel compData = new DataLibrary.Models.CompetitionModel();
                compData.Title = newComp.Title;
                compData.Date = newComp.Date.GetValueOrDefault();
                compData.Description = newComp.Description;
                compData.GameID = gameID;
                DataLibrary.DataAccess.SQLDataAccess.CreateCompetition(compData);

                return RedirectToAction("AdminHome", "Home");
            }
            
            return View(newComp);
        }

        public IActionResult CompetitionInfo(int CompID)
        {
            CompetitionModel comp = new CompetitionModel();
            DataLibrary.Models.CompetitionModel compData = 
                DataLibrary.DataAccess.SQLDataAccess.GetCompetition(CompID);
            comp.strDate = compData.Date.ToString("MM/dd/yyyy");
            comp.Description = compData.Description;
            comp.GameID = compData.GameID;
            comp.CompID = compData.CompID;
            comp.GameTitle = compData.GameTitle;
            comp.IsEntered = false;
            comp.Title = compData.Title;

            if (HttpContext.Session.Get("Username") != null)
            {
                string Username = HttpContext.Session.GetString("Username");
                comp.IsEntered = DataLibrary.DataAccess.SQLDataAccess.EnteredComp(CompID, Username);
            }

            comp.EnteredPlayers = DataLibrary.DataAccess.SQLDataAccess.GetEnteredPlayers(CompID);

            return View(comp);
        }

        public IActionResult EnterCompetition(int CompID)
        {
            if (HttpContext.Session.Get("Username") == null)
                return RedirectToAction("Index", "Login");

            string Username = HttpContext.Session.GetString("Username");
            DataLibrary.DataAccess.SQLDataAccess.EnterCompetition(CompID, Username);

            return RedirectToAction("CompetitionInfo", new { CompID = CompID });
        }

        public IActionResult LeaveCompetition(int CompID)
        {
            string Username = HttpContext.Session.GetString("Username");
            DataLibrary.DataAccess.SQLDataAccess.LeaveCompetition(CompID, Username);

            return RedirectToAction("CompetitionInfo", new { CompID = CompID });
        }

        public IActionResult EditCompetition(int CompID)
        {
            CompetitionModel comp = new CompetitionModel();
            DataLibrary.Models.CompetitionModel compData =
                DataLibrary.DataAccess.SQLDataAccess.GetCompetition(CompID);
            comp.Date = compData.Date;
            comp.Description = compData.Description;
            comp.GameID = compData.GameID;
            comp.CompID = compData.CompID;
            comp.GameTitle = compData.GameTitle;
            comp.Title = compData.Title;

            return View(comp);
        }

        [HttpPost]
        public IActionResult EditCompetition(CompetitionModel comp)
        {
            int GameID = DataLibrary.DataAccess.SQLDataAccess.getGameID(comp.GameTitle);
            if (GameID == 0)
                ModelState.AddModelError("GameTitle", "Game does not exist. Check name and try again.");

            if(ModelState.IsValid)
            {
                DataLibrary.Models.CompetitionModel compData = new DataLibrary.Models.CompetitionModel();
                compData.CompID = comp.CompID;
                compData.Date = comp.Date.GetValueOrDefault();
                compData.Description = comp.Description;
                compData.GameID = GameID;
                compData.Title = comp.Title;
                DataLibrary.DataAccess.SQLDataAccess.EditCompetition(compData);

                return RedirectToAction("CompetitionInfo", new { CompID = comp.CompID });
            }

            return View(comp);
        }

        [HttpPost]
        public IActionResult RemoveCompetition(int CompID)
        {
            string Username = HttpContext.Session.GetString("Username");
            DataLibrary.DataAccess.SQLDataAccess.RemoveCompetition(CompID);

            return RedirectToAction("Competitions", "Marketplace");
        }
    }
}

Fog/Views/Competition/CompetitionInfo.cshtml
@using Microsoft.AspNetCore.Http;
@model Fog.Models.CompetitionModel
@{
    ViewData["Title"] = "Competition Info";
}

<h1 class="text-center">@Model.Title</h1>

<div class="row justify-content-center">
    <h4>Game: @Model.GameTitle</h4>
</div>
<div class="row justify-content-center">
    <h4>Date: @Model.strDate</h4>
</div>
<div class="row justify-content-center">

    <textarea rows="8" style="min-width: 100%; resize:none" readonly>@Model.Description</textarea>
</div>
<div class="row justify-content-center mt-4">
    <h4>Entered Players:</h4>
</div>
<div class="row justify-content-center" style="height:200px; overflow:auto">
    <table class="table">
        <thead>
            <tr>
                <th>Player Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.EnteredPlayers)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DisplayName)
                    </td>
                    <td>
                        @Html.ActionLink("Info", "PlayerInfo", "Home", new { playerUsername = item.Username })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@if (Context.Session.Get("Username") != null && Context.Session.GetInt32("Permission") == 2)
{
    <div class="row justify-content-center mb-2">
        <div class="col-4">
            <button type="button" class="btn btn-dark btn-block"
                    onclick="location.href='@Url.Action("EditCompetition", "Competition",
                                                new { CompID = Model.CompID })'">
                Edit Competition
            </button>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-4">
            <button type="button" class="btn btn-dark btn-block" data-toggle="modal" data-target="#RemoveCompModal">
                Remove Competition
            </button>
        </div>
    </div>
}
else
{
    @if (Model.IsEntered)
    {
        <div class="row justify-content-center">
            <div class="col-4">
                <button type="button" class="btn btn-dark btn-block"
                        onclick="location.href='@Url.Action("LeaveCompetition", "Competition",
                                                new { CompID = Model.CompID })'">
                    Leave Competition
                </button>
            </div>
        </div>
    }
    else
    {
        <div class="row justify-content-center">
            <div class="col-4">
                <button type="button" class="btn btn-dark btn-block"
                        onclick="location.href='@Url.Action("EnterCompetition", "Competition",
                                                new { CompID = Model.CompID })'">
                    Enter Competition
                </button>
            </div>
        </div>
    }
}

<div class="modal fade" id="RemoveCompModal" tabindex="-1" role="dialog"
     aria-labelledby="removeCompModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="removeCompModalLabel">Remove Competition</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-center">
                <p>Are you sure you want to remove this Competition?</p>
                <p>This action cannot be undone.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Keep Competition</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal"
                        onclick="location.href='@Url.Action("RemoveCompetition", "Competition",
                                                new { CompID = Model.CompID })'">
                    Remove Competition
                </button>
            </div>
        </div>
    </div>
</div>

Fog/Views/Competition/CreateCompetition.cshtml
@model Fog.Models.CompetitionModel
@{
    ViewData["Title"] = "Create Competition";
}

<h1>@ViewData["Title"]</h1>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateCompetition">
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="GameTitle" class="control-label"></label>
                <input asp-for="GameTitle" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" rows="10" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Fog/Views/Competition/EditCompetition.cshtml
@model Fog.Models.CompetitionModel
@{
    ViewData["Title"] = "Edit Competition";
}

<h1>Edit Competition</h1>

<form asp-action="EditCompetition">
    <input type="hidden" asp-for="CompID">
    <div class="form-group">
        <label asp-for="Title" class="control-label"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Date" class="control-label"></label>
        <input asp-for="Date" class="form-control" />
        <span asp-validation-for="Date" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="GameTitle" class="control-label"></label>
        <input asp-for="GameTitle" class="form-control" />
        <span asp-validation-for="GameTitle" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <textarea class="form-control" asp-for="Description" rows="10" style="min-width: 100%; resize:none"></textarea>
    </div>
    <div class="form-group">
        <input type="submit" value="Submit" class="btn btn-primary" />
    </div>
</form>